// Generated by CoffeeScript 1.8.0
(function() {
  var gulp, livereload, paths, plumber, watch;

  gulp = require('gulp');

  watch = require('gulp-watch');

  plumber = require('gulp-plumber');

  livereload = require('gulp-livereload');

  paths = {
    scripts: './lib/**/*.coffee'
  };

  gulp.task("watch", function() {
    var server;
    server = livereload();
    return gulp.watch(paths.scripts).on('change', function(file) {
      return server.changed(file.path);
    });
  });

  gulp.task("default", ['watch']);

}).call(this);

//# sourceMappingURL=Gulpfile.js.map
