// Generated by CoffeeScript 1.8.0
(function() {
  var Docpad, configDefaults;

  Docpad = require('/var/www/atom/project/node_modules/docpad');

  configDefaults = {
    rootPath: '/var/www/atom/project/'
  };

  process.env['NODE_ENV'] = 'production';

  console.log(process.env['NODE_ENV']);

  Docpad.createInstance(configDefaults, function(err, docpadInstance) {
    if (err) {
      return console.log(err.stack);
    }
    docpadInstance.on('notify', function(opt) {
      return console.log(opt.options.title);
    });
    return docpadInstance.action('run', function(err) {
      if (err) {
        return console.log(err.stack);
      }
    });
  });

}).call(this);

//# sourceMappingURL=docpad-child.js.map
